Change internal contracts to interface
conflux-fans/conflux-contracts pull request #22
Opened 2021-10-30 08:26 UTC by Pana

2021-11-01 03:45 UTC, boqiu requested changes

2021-11-01 03:45 UTC, boqiu commented on contracts/InternalContracts/Staking.sol
> +    function deposit(uint256 amount) external payable;
Should not be `payable`.

2021-11-01 05:15 UTC, boqiu approved these changes

2021-11-02 08:52 UTC, wangdayong228 approved these changes

2021-11-02 08:52 UTC, merged